version: 2
updates:  
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
  
  # Maintain dependencies for Windows GUI nuget
  - package-ecosystem: "nuget"
    directory: "win/CS"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
