name: "Push Notification"
on:
  push:
  pull_request:
      types: [opened, review_requested]

jobs:
  Send_IRC_Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Commit
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push' && github.repository == 'HandBrake/HandBrake'
        with:
          channel: "#handbrake"
          nickname: handbrake-bot
          server: chat.freenode.net
          port: 6697
          tls: true
          message: |
            COMMIT: ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} ${{ join(github.event.commits.*.message) }}
      - name: Handle Pull Request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request' && github.repository == 'HandBrake/HandBrake'
        with:
          channel: "#handbrake"
          nickname: handbrake-bot
          server: chat.freenode.net
          port: 6697
          tls: true
          message: |
            PULL REQUEST: ${{ github.actor }} ${{ github.event.action }} a Pull Request ${{ github.event.pull_request.html_url }}
